# Generated by Django 5.2.11 on 2026-03-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="введите email существующего сервиса.",
                max_length=254,
                unique=True,
                verbose_name="email-адрес",
            ),
        ),
    ]
