# Generated by Django 5.2.11 on 2026-02-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("genre", models.CharField(blank=True, max_length=100)),
                ("publication_year", models.IntegerField(blank=True)),
            ],
            options={
                "db_table": "books",
                "managed": False,
            },
        ),
    ]
