# Generated by Django 5.2.11 on 2026-02-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "книга", "verbose_name_plural": "книги"},
        ),
        migrations.AlterField(
            model_name="book",
            name="publication_year",
            field=models.IntegerField(null=True),
        ),
    ]
